language: node_js
node_js:
  - 12
install:
  - npm install
before_script:
  - npm run build
script:
  - npm run test
after_success:
  - npm run coverall
env:
  global:
    secure: nTe7rKQaQfbYy47A2LYHTUTf8BtUHdh0fxf30WXPNI8aq15dkmcFV1zO4VMhh5SmIjJm1Cr/hDIX9FCh7BR5e57Eg/sTA81tK81Ys4SSmuy0TAkbTR4ulhfx9izeyQtYZufa7kH+XbOyrftQAcn0IsccxjbyjFvgWJBH/3n8gszOUogTcpRId7HOZ6h2neCZBh9F4zlxu3/Dd+8ngVq2HC4kWyFCb1xG2pr2wyQX1E9VrLfHw59Nwt9RlQ6A0ywG8HOo4w8vdVlF2JQCvm/4h8DM6dCT7j8+GGgbdP76lXtezrcdsxD1bAiL9YHL/YPJGY9azNsWa+WkOYeoX1+toUJVqqBYpTWZn7XLvFR5O+OnfKjROT+zItSDJhIUz5W8EreOIB0XeW5mCU69gmOMy2/E1uohbnb081ofBrRRWkwB5pUjz3Q3z7naV1xDkDk1q5vHT5OzCqFQIqE2ETYlduiQ2EEmiL+UheR0DnEpVARGLCym/EnyaNuqYci2ck2g/oSvteRBOVIG4CEunYPfq/PfDMGRU2HpeX4drgGq5PMxGpnCORVGGSVrs21vNQnfCVPpHja7xGqiJCNbwtrdeM1Axd5Cu0r9INeOuA2KDoMy6lKiabLcT+4RMPBF0CeRAr4RV9wYZ5vAGIULhDFDo4y+IDUoYDgUNSSaP5lTxcg=
